# Generated by Django 3.1.11 on 2021-10-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bearcatE', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
